spec:
  destination:
    server: https://kubernetes.default.svc
    project: manage
  source:
    repoURL: https://smhhoseinee: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@github.com/smhhoseinee/apps.git
    # repoURL: https://github.com/mbarazandeh110/apps-skyroom.git
    # repoURL: https://github.com/SkyroomOnline/apps-skyroom.git
    targetRevision: HEAD
